name: Hive
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^10.3.0
  path_provider: ^2.0.11
  mysql1: ^0.20.0
  http: ^1.2.2
  shared_preferences: ^2.3.5
  biometric_login: ^0.0.1
  local_auth: ^2.3.0
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  add_2_calendar: ^2.1.0
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.0.4
  url_launcher: ^6.2.5
  intl: ^0.18.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/type_icons/
    - assets/honeycoins.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"